export default {
    UPDATE_FECHA:'UPDATE_FECHA',
    //ACCIONES PARA ESTRENOS
    GET_ESTRENOS:           'GET_ESTRENOS',
    GET_ESTRENOS_PENDING:   'GET_ESTRENOS_PENDING',
    GET_ESTRENOS_FULFILLED: 'GET_ESTRENOS_FULFILLED',
    GET_ESTRENOS_REJECTED:  'GET_ESTRENOS_REJECTED',
    //ACCIONES PARA PROXIMOS ESTRENOS
    GET_PROXIMOS_ESTRENOS:          'GET_PROXIMOS_ESTRENOS',
    GET_PROXIMOS_ESTRENOS_PENDING:  'GET_PROXIMOS_ESTRENOS_PENDING',
    GET_PROXIMOS_ESTRENOS_FULFILLED:'GET_PROXIMOS_ESTRENOS_FULFILLED',
    GET_PROXIMOS_ESTRENOS_REJECTED: 'GET_PROXIMOS_ESTRENOS_REJECTED',
    //ACCIONES PARA CREDITOS
    GET_CREDITOS:          'GET_CREDITOS',
    GET_CREDITOS_PENDING:  'GET_CREDITOS_PENDING',
    GET_CREDITOS_FULFILLED:'GET_CREDITOS_FULFILLED',
    GET_CREDITOS_REJECTED: 'GET_CREDITOS_REJECTED',
    //ACCIONES PARA DETALLES
    GET_PELICULA_DETALLE:          'GET_PELICULA_DETALLE',
    GET_PELICULA_DETALLE_PENDING:  'GET_PELICULA_DETALLE_PENDING',
    GET_PELICULA_DETALLE_FULFILLED:'GET_PELICULA_DETALLE_FULFILLED',
    GET_PELICULA_DETALLE_REJECTED: 'GET_PELICULA_DETALLE_REJECTED',
    //ACCIONES PARA BUSQUEDA
    GET_BUSQUEDA:          'GET_BUSQUEDA',
    GET_BUSQUEDA_PENDING:  'GET_BUSQUEDA_PENDING',
    GET_BUSQUEDA_FULFILLED:'GET_BUSQUEDA_FULFILLED',
    GET_BUSQUEDA_REJECTED: 'GET_BUSQUEDA_REJECTED',
    //LIMPIEZA
    CLEAR_SEARCH:'CLEAR_SEARCH'
}